version: '3.7'
services:
   app:
    container_name: mongodb_container
    image: mongo:4.2.16
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks: 
      backend: 
        aliases: 
          - mongodb_host

networks:
  backend: 
    name: backend_network
    driver: bridge

volumes:
  mongodb_data_container:
