FROM node:14-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
# RUN npm i express graphql express-graphql
# RUN npm i  mongoose dotenv jsonwebtoken
# RUN npm i cookie-parser
# RUN npm i --save-dev  nodemon
# RUM sudo npm i -g pm2
RUN yarn install
# RUN node -r dotenv/config ./src/config.env
# Copy app files
COPY . .
# Expose port
EXPOSE 3050
# Start the app
CMD [ "yarn", "dev" ]